Repository punyakrit/social-share, pull requests merged in 2024-05, with the labels that each got.

#8 Updated README.md File
  README.md
  Share_hub.png
Labels: gssoc, level1

#10 Added CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc, level1

#33 Created Footer with legal and policy page
  app/layout.tsx
  app/page.tsx
  app/policy/page.tsx
  app/terms_conditions/page.tsx
  components/FooterApp.tsx
Labels: gssoc, level2

#43 added hover on icons on footer and changed size of icon.
  components/FooterApp.tsx
Labels: gssoc

#47 Create Learn.md
  Learn.md
Labels: gssoc, level1

#52 Text and Button animation
  components/HeroText.tsx
  components/UserNameForm.tsx
  components/pages/Home.tsx
  components/ui/MagicButton.tsx
  components/ui/TypeWriter.tsx
Labels: gssoc, level2

#53 Added similarity to footer links
  components/FooterApp.tsx
Labels: gssoc, level1

#54 Added href to footer links
  components/FooterApp.tsx
Labels: gssoc
