Repository punyakrit/social-share, pull requests merged in 2024-07, with the labels that each got.

#173 Added Toast wherever required
  app/(app)/layout.tsx
  components/DashboardLogout.tsx
  components/UserLogoutButton.tsx
  components/pages/Contact.tsx
  components/pages/Home.tsx
  components/pages/UserForm.tsx
  package-lock.json
  package.json
Labels: gssoc, level2

#172 N
  components/pages/404.tsx
Labels: gssoc, level1

#180 [Bug]: home page needs to be responsive #152
  components/Appbar.tsx
  components/pages/Home.tsx
Labels: gssoc, level1

#175 button aligned properly
  components/UserNameForm.tsx
  components/ui/MagicButton.tsx
  tailwind.config.ts
Labels: gssoc, level1

#187 DOC: Link important .md files to main readme (Issue #181)
  README.md
Labels: gssoc, level1

#192 added dockerfile and dockercompose
  .env.example
  Dockerfile
  components/pages/About.tsx
  docker-compose.yml
Labels: gssoc, level2

#194 Adjusted the alignment at different screen sizes.
  app/(landing)/onboarding/page.tsx
  tailwind.config.ts
Labels: gssoc, level1

#201 Added contributing steps in readme
  README.md
Labels: gssoc, level1

#203 Issue#176 fixed. Added Faq page.
  app/(landing)/faq/page.tsx
  components/Appbar.tsx
  components/pages/Faq.tsx
  components/ui/accordion.tsx
  package-lock.json
  package.json
Labels: gssoc, level3

#202 Button and Sidebar are adjusted Properly.
  components/UserNameForm.tsx
  components/sidebarmobileview.tsx
  components/ui/GoToDashboardButton.tsx
  components/ui/MagicButton.tsx
Labels: gssoc, level2

#200 form validation sucess
  components/pages/Contact.tsx
  package-lock.json
  tsconfig.json
Labels: gssoc, level2

#208 FAQ alligned properly for small screens
  components/ui/accordion.tsx
Labels: gssoc, level1

#207 feat: added toasts on profile updates
  components/dashboard/UserLinks.tsx
  components/dashboard/UserSettings.tsx
  components/dashboard/UserSocialForm.tsx
Labels: gssoc, level2

#205 added input center in responsive devices
  components/UserNameForm.tsx
Labels: gssoc, level1

#213 FAQs option is added in the hamburger menu.
  components/sidebarmobileview.tsx
Labels: gssoc, level1

#214 contact information stored in database
  app/api/contact/route.ts
  components/pages/Contact.tsx
  lib/db.ts
  package-lock.json
  package.json
Labels: gssoc, level2

#216 fix: prevent unnecessary API calls on profile update
  components/dashboard/UserLinks.tsx
  components/dashboard/UserSettings.tsx
  components/dashboard/UserSocialForm.tsx
  package-lock.json
Labels: gssoc, level3

#215 Bug : Fixed
  components/FooterApp.tsx
Labels: gssoc, level1

#219 feat: popover on clicking avatar
  components/UserLogoutButton.tsx
  components/UserProfile.tsx
  components/ui/PopoverCard.tsx
  package-lock.json
  package.json
Labels: gssoc, level2

#222 Added Newsletter Subscription to Footer
  .env.example
  Dockerfile
  components/FooterApp.tsx
  docker-compose.yml
  next.config.mjs
  package-lock.json
  package.json
Labels: gssoc, level2

#225 add pagination as well as user interface update
  .env.example
  components/pages/Contributors.tsx
Labels: gssoc, level2

#230 feat: validate social links
  components/dashboard/UserSocialForm.tsx
Labels: gssoc, level2

#229 email subscriptions added
  app/api/subscribe/route.ts
  components/FooterApp.tsx
  package-lock.json
  package.json
Labels: gssoc, level2

#237 truncate added in contributor card username
  components/pages/Contributors.tsx
Labels: gssoc, level1

#238 Fixed the homepage for mobile screen
  components/UserNameForm.tsx
  components/pages/Home.tsx
  components/ui/background-beams.tsx
Labels: gssoc, level2

#239 added phone no validation number should not be more than 10 digits
  components/pages/Contact.tsx
Labels: gssoc, level1

#240 Added open FAQ on hover
  components/ui/accordion.tsx
Labels: gssoc, level2

#241 Added skeleton for contributor
  components/pages/Contributors.tsx
  components/pages/SkeletonContributor.tsx
Labels: gssoc, level2

#242 changed the design of the form input and alignment
  app/globals.css
  components/FooterApp.tsx
Labels: gssoc, level2

#245 fix: profile page responsive + text ellipsis
  app/(profile)/[profile]/page.tsx
Labels: gssoc, level1

#247 fix: image upload labels
  app/globals.css
  components/FooterApp.tsx
Labels: gssoc, level1

#248 perfectly alligned contact page for all screen and redesigned a little
  components/pages/Contact.tsx
Labels: gssoc, level1
