Repository punyakrit/social-share, pull requests merged in 2024-06, with the labels that each got.

#58 Resized the cursor and made it responsive and changed X icon
  .env.example
  components/FooterApp.tsx
  components/ui/TypeWriter.tsx
  components/ui/XIcon.tsx
Labels: gssoc, level1

#61 Added "Privacy Policy" page
  app/(policy)/layout.tsx
  app/(policy)/policy/page.tsx
Labels: gssoc, level2

#62 Added "Terms and Conditions" page
  app/(policy)/layout.tsx
  app/(policy)/terms_conditions/page.tsx
Labels: gssoc, level2

#71 Added erase effects to the hero text
  components/HeroText.tsx
  components/ui/TypeWriter.tsx
Labels: gssoc, level2

#73 Added custom scroll bar
  app/globals.css
Labels: gssoc, level1

#78 Update README.md
  README.md
Labels: gssoc, level1

#80 Adding Issue Template
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/other.yml
Labels: gssoc, level1

#86 fixed spelling of `linkedin`
  components/FooterApp.tsx
Labels: gssoc

#89 Updated favicon
  app/favicon.ico
Labels: gssoc, level1

#94 Create contributing.md
  contributing.md
Labels: gssoc, level1

#93 Create pull-request.md
  .github/ISSUE_TEMPLATE/pull-request.md
Labels: gssoc, level1

#95 Created About Us page, Explore page and contact us page, fixed navbar issues
  app/(landing)/about/page.tsx
  app/(landing)/contact/page.tsx
  app/(landing)/explore/page.tsx
  app/(landing)/layout.tsx
  components/Aboutstyles.css
  components/Appbar.tsx
  components/Contactstyles.css
  components/Explorestyle.css
  components/GoogleLoginButton.tsx
  components/HeroText.tsx
  components/Like.tsx
  components/Likestyle.css
  components/UserLogoutButton.tsx
  components/UserNameForm.tsx
  components/assets/contactlottie.json
  components/assets/lottieabout.json
  components/pages/About.tsx
  components/pages/Contact.tsx
  components/pages/Explore.tsx
  components/pages/Home.tsx
  components/ui/MagicButton.tsx
  components/ui/TypeWriter.tsx
  next.config.mjs
  package-lock.json
  package.json
  tailwind.config.ts
Labels: gssoc, level3

#100 home page mobile view fixed
  components/Appbar.tsx
  components/UserNameForm.tsx
Labels: gssoc, level1

#102 Updated README.md file
  README.md
  Screenshot 2024-06-07 at 11.14.04 AM.png
  image-3.png
  image-4.png
  image-5.png
  image.png
Labels: gssoc, level1

#101 Added Hamburger / Side Bar when screen is medium and small
  app/(app)/layout.tsx
  components/dashboard/AppBar.tsx
  components/dashboard/DashboardSectionComponent.tsx
  components/dashboard/SideBar.tsx
  components/dashboard/SideBarHeader.tsx
  components/dashboard/UserSettings.tsx
Labels: gssoc, level2

#104 added show more icon in mobile view
  components/Appbar.tsx
  components/sidebarmobileview.css
  components/sidebarmobileview.tsx
Labels: gssoc, level2

#112 Create LICENSE
  LICENSE
Labels: gssoc, level1

#119 changed icons in aboutUS
  components/pages/About.tsx
Labels: gssoc, level1

#121 Enhanced background
  components/Appbar.tsx
  components/HeroText.tsx
  components/pages/Home.tsx
  components/ui/background-beams.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: gssoc, level2

#125 Contact Page Form Aligned Properly
  components/pages/Contact.tsx
Labels: gssoc

#127 Improve Error Handling and Type Checking in User Profile Update Functions
  actions/UserProfile.ts
Labels: gssoc, level2

#135 Added HOME in navbar
  components/Appbar.tsx
  components/sidebarmobileview.tsx
Labels: gssoc, level1

#139 Added "licensing" Page Reflecting "MIT License"
  app/(policy)/licensing/page.tsx
  components/FooterApp.tsx
Labels: gssoc, level2

#143 Added Footer Description
  components/FooterApp.tsx
Labels: gssoc, level1

#144 Hamburger icon should replace with close icon if dialog open up after click on hamburger #120
  app/globals.css
  components/sidebarmobileview.tsx
  package-lock.json
  package.json
Labels: gssoc, level1

#145 Sending username from landing page to onboarding screen
  components/pages/UserForm.tsx
Labels: gssoc, level1

#146 Hover effects added
  components/pages/About.tsx
Labels: gssoc, level1

#158 Added Transform hover to the Footer Links
  app/globals.css
  components/FooterApp.tsx
Labels: gssoc, level2

#153 Implement "Back to Home" Button for the Application
  app/(app)/layout.tsx
  app/(policy)/licensing/page.tsx
  app/(policy)/policy/page.tsx
  app/(policy)/terms_conditions/page.tsx
  app/globals.css
  components/BackToHome.tsx
Labels: gssoc, level2

#163 Fixed the borke dashboard UI
  app/(app)/layout.tsx
Labels: gssoc, level1

#168 Added Fevicon to the Website
  app/favicon.ico
  public/favicon.ico
Labels: gssoc, level1
